[tools]
python = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true

[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"

# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true }

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
'''

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv pip install -r requirements.txt"

[tasks.setup-dev]
description = "Set up development environment with uv"
run = '''
uv venv .venv
uv pip install -e ".[dev]"
'''

[tasks.run]
description = "Run the application"
run = "python -m mflux_commander.cli.main"

[tasks.dev]
description = "Run the application in development mode with the installed package"
run = "pip install -e . && mflux-commander"

[tasks.test]
description = "Run tests"
run = "python -m pytest"